name: checks
on: [pull_request, push]
jobs:
  should_skip_check:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.skip.outputs.should_skip }}
    steps:
      - id: skip
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'always'
  check:
    needs: should_skip_check
    if: ${{ needs.should_skip_check.outputs.result != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: nvmrc
        run: echo "::set-output name=version::$(cat .nvmrc)"
      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: ${{ steps.nvmrc.outputs.version }}
      - run: yarn install
      - run: yarn run check