name: checks
on: [pull_request, push]
jobs:
  quick:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: nvmrc
        run: echo "::set-output name=nvmrc::$(cat .nvmrc)"
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvmrc.outputs.nvmrc }}
      - name: Get yarn cache
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-yarn-${{ steps.nvmrc.outputs.nvmrc }}-${{ hashFiles('**/yarn.lock') }}
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          restore-keys: ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile --silent
      - run: yarn run check