name: checks
on: [pull_request, push]
concurrency: 
  cancel-in-progress: true
  group: ${{ github.ref }}
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: nvmrc
        run: echo "::set-output name=version::$(cat .nvmrc)"
      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: ${{ steps.nvmrc.outputs.version }}
      - run: yarn install
      - run: yarn run check